"""
Trading Engine - orchestrates strategy execution, signal generation, and broker interactions.

This is the core logic that ties together:
- Strategy genome (entry/exit rules)
- Broker interface (Alpaca or other)
- IPC channel (orchestrator communication)
- Position management

The engine is broker-agnostic - it only knows about the BrokerInterface.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any, Callable, Awaitable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum

from ..executor.interfaces import BrokerInterface, Position, OrderSide, BracketOrderRequest
from ..ipc.channel import IPCChannel, CommandType
from trading_system.executor.rule_engine import evaluate_rule
from trading_system.executor.indicators import compute_indicators


logger = logging.getLogger(__name__)


class EngineState(Enum):
    STARTING = "starting"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPING = "stopping"
    STOPPED = "stopped"


@dataclass
class ActivePosition:
    """Track an active position managed by the engine"""
    symbol: str
    qty: float  # Changed to float for fractional
    entry_price: float
    entry_bar: int
    entry_time: datetime
    entry_signal_strength: float
    is_fractional: bool = False
    synthetic_tp_price: Optional[float] = None
    synthetic_sl_price: Optional[float] = None
    bracket_order_id: Optional[str] = None
    trailing_stop_order_id: Optional[str] = None
    extended_bars: int = 0
    
    @property
    def bars_held(self) -> int:
        return (datetime.utcnow() - self.entry_time).days
    
    @property
    def unrealized_pnl_pct(self) -> float:
        # Current price would be fetched separately
        return 0.0  # Placeholder


@dataclass
class Signal:
    """Trading signal generated by the engine"""
    symbol: str
    action: str  # "entry", "exit", "hold_extension"
    confidence: float  # 0-1
    reason: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict = field(default_factory=dict)


class TradingEngine:
    """
    Main trading engine.
    
    Responsible for:
    1. Loading and parsing strategy genomes
    2. Computing indicators from market data
    3. Evaluating entry/exit rules
    4. Managing positions (via broker)
    5. Handling orchestrator commands via IPC
    6. Emitting alerts for human-in-the-loop decisions
    """
    
    def __init__(
        self,
        broker: BrokerInterface,
        strategy_genome: Dict,
        ipc_channel: Optional[IPCChannel] = None,
        config: Optional[Dict] = None,
    ):
        self.broker = broker
        self.strategy = strategy_genome
        self.ipc = ipc_channel or IPCChannel()
        self.config = config or {}
        
        # Extract strategy parameters
        self.symbols = self.config.get("symbols", [])
        self.lookback_bars = self.config.get("lookback_bars", 100)
        
        # Risk parameters
        rm = strategy_genome.get("risk_management", {})
        self.max_hold_soft = rm.get("max_hold_bars_soft", 3)
        self.max_hold_hard = rm.get("max_hold_bars", 5)
        self.stop_loss_pct = rm.get("stop_loss_pct", 0.07)
        self.take_profit_pct = rm.get("take_profit_pct", 0.197)
        
        ps = strategy_genome.get("position_sizing", {})
        self.max_position_pct = ps.get("max_pct", 0.10)
        
        # State
        self.state = EngineState.STARTING
        self.positions: Dict[str, ActivePosition] = {}
        self.signal_history: List[Signal] = []
        
        # Callbacks
        self.on_signal: Optional[Callable[[Signal], None]] = None
        self.on_alert: Optional[Callable[[str, str, Dict], None]] = None
        
        logger.info(f"[Engine] Initialized with strategy: {strategy_genome.get('name', 'unknown')}")
        logger.info(f"[Engine] Max hold: {self.max_hold_soft} (soft) / {self.max_hold_hard} (hard) bars")
    
    def calculate_position_size(self, symbol: str, current_price: float, use_fractional: bool = True) -> float:
        """Calculate fractional (or integer) position size based on account equity and risk parameters"""
        account = self.broker.get_account()
        equity = account["equity"]
        
        # Total equity we want to risk on this one trade
        risk_amount = equity * self.max_position_pct
        
        # Qty required to hit the target risk
        qty = risk_amount / (self.stop_loss_pct * current_price)
        
        if not use_fractional:
            qty = max(1, int(qty))
            
        return round(qty, 4)
    
    def evaluate_entry(self, symbol: str, market_data: Dict) -> Optional[Signal]:
        """
        Evaluate entry rule for a symbol.
        
        Returns a Signal if entry rule fires, None otherwise.
        """
        entry_rule = self.strategy.get("entry_rule")
        if not entry_rule:
            return None
        
        indicators = self.strategy.get("indicators", [])
        df_indicators = compute_indicators(market_data, indicators, symbol=symbol, broker=self.broker)
        
        # Merge market data with indicators
        context = {**market_data, **df_indicators}
        
        result = evaluate_rule(context, entry_rule, indicators)
        
        if result:
            return Signal(
                symbol=symbol,
                action="entry",
                confidence=0.8,  # Could be enhanced with model confidence
                reason="Entry rule satisfied",
                metadata={"rule": "entry", "indicators": df_indicators},
            )
        
        return None
    
    def evaluate_exit(self, symbol: str, market_data: Dict, position: ActivePosition) -> Optional[Signal]:
        """
        Evaluate exit rule for a symbol given an active position.
        
        Returns a Signal if exit rule fires, None otherwise.
        """
        exit_rule = self.strategy.get("exit_rule")
        if not exit_rule:
            return None
        
        indicators = self.strategy.get("indicators", [])
        df_indicators = compute_indicators(market_data, indicators, symbol=symbol, broker=self.broker)
        
        context = {**market_data, **df_indicators}
        
        result = evaluate_rule(context, exit_rule, indicators)
        
        if result:
            return Signal(
                symbol=symbol,
                action="exit",
                confidence=0.9,
                reason="Exit rule satisfied",
                metadata={"rule": "exit", "bars_held": position.bars_held},
            )
        
        return None
    
    def check_extension_criteria(self, symbol: str, market_data: Dict, position: ActivePosition) -> Optional[Signal]:
        """
        Check if position should be extended beyond soft limit.
        
        This is where the engine decides to alert the orchestrator for a human decision.
        """
        bars_held = position.bars_held
        
        # Not at soft limit yet
        if bars_held < self.max_hold_soft:
            return None
        
        # At or past hard limit - should exit regardless
        if bars_held >= self.max_hold_hard:
            return Signal(
                symbol=symbol,
                action="exit",
                confidence=1.0,
                reason=f"Hard limit reached ({bars_held} bars)",
                metadata={"bars_held": bars_held, "force": True},
            )
        
        # At soft limit - check for extension criteria
        # This is a simplified version - could be enhanced with ML model confidence
        current_price = market_data.get("close", 0)
        entry_price = position.entry_price
        pnl_pct = (current_price - entry_price) / entry_price if entry_price else 0
        
        # Extension criteria: profitable and holding well
        if pnl_pct > 0.03:  # >3% profit
            return Signal(
                symbol=symbol,
                action="hold_extension",
                confidence=0.7,
                reason=f"Profitable ({pnl_pct:.1%}) at soft limit, orchestrator decision needed",
                metadata={
                    "bars_held": bars_held,
                    "pnl_pct": pnl_pct,
                    "entry_price": entry_price,
                    "current_price": current_price,
                },
            )
        
        return None
    
    def open_position(
        self,
        symbol: str,
        qty: float,
        current_price: float,
        side: OrderSide = OrderSide.BUY,
    ) -> bool:
        """Open a new position. Supports fractional with synthetic brackets, or integers with native brackets."""
        
        # Calculate TP and SL prices
        if side == OrderSide.BUY:
            tp_price = round(current_price * (1 + self.take_profit_pct), 2)
            sl_price = round(current_price * (1 - self.stop_loss_pct), 2)
        else:
            tp_price = round(current_price * (1 - self.take_profit_pct), 2)
            sl_price = round(current_price * (1 + self.stop_loss_pct), 2)
            
        fractional = isinstance(qty, float) and not qty.is_integer()
        
        if fractional:
            # Alpaca API blocks native brackets on fractional qty.
            # We submit a plain Market Order, then track synthetic SL/TP internally.
            from trading_system.executor.interfaces import BracketOrderRequest # Just for typing matching
            try:
                # We use the broker's underlying client to send a pure market order
                logger.debug(f"Submitting fractional order to {symbol} (qty: {qty})")
                order = self.broker.client.submit_order(
                    symbol=symbol,
                    qty=str(round(qty, 4)),
                    side="buy" if side == OrderSide.BUY else "sell",
                    type="market",
                    time_in_force="day"
                )
                
                self.positions[symbol] = ActivePosition(
                    symbol=symbol,
                    qty=qty,
                    entry_price=current_price,
                    entry_bar=0,
                    entry_time=datetime.utcnow(),
                    entry_signal_strength=0.8,
                    is_fractional=True,
                    synthetic_tp_price=tp_price,
                    synthetic_sl_price=sl_price,
                )
                logger.info(f"[Engine] Opened FRACTIONAL {symbol} @ {current_price}, qty={qty:.4f}, (Synthetic) TP={tp_price:.2f}, SL={sl_price:.2f}")
                return True
            except Exception as e:
                logger.error(f"[Engine] Failed to open synthetic fractional position for {symbol}: {e}")
                return False
        else:
            # Native Bracket Order Logic
            bracket_req = BracketOrderRequest(
                symbol=symbol,
                side=side,
                qty=int(qty),
                order_type="market",
                take_profit_limit_price=tp_price,
                stop_loss_stop_price=sl_price,
            )
            
            try:
                order = self.broker.submit_bracket_order(bracket_req)
                
                # Track position
                self.positions[symbol] = ActivePosition(
                    symbol=symbol,
                    qty=int(qty),
                    entry_price=current_price,
                    entry_bar=0,  # Would use actual bar count
                    entry_time=datetime.utcnow(),
                    entry_signal_strength=0.8,
                    bracket_order_id=order.id,
                )
                
                logger.info(f"[Engine] Opened {symbol} @ {current_price}, qty={int(qty)}, TP={tp_price:.2f}, SL={sl_price:.2f}")
                return True
                
            except Exception as e:
                logger.error(f"[Engine] Failed to open position for {symbol}: {e}")
                return False
    
    def close_position(self, symbol: str, reason: str = "signal") -> bool:
        """Close an existing position"""
        if symbol not in self.positions:
            logger.warning(f"[Engine] No position to close for {symbol}")
            return False
        
        try:
            self.broker.close_position(symbol)
            
            pos = self.positions.pop(symbol)
            logger.info(f"[Engine] Closed {symbol}, reason: {reason}")
            
            # Emit alert
            self.ipc.write_alert(
                alert_type="POSITION_CLOSED",
                symbol=symbol,
                data={
                    "reason": reason,
                    "qty": pos.qty,
                    "entry_price": pos.entry_price,
                    "bars_held": pos.bars_held,
                },
            )
            
            return True
            
        except Exception as e:
            logger.error(f"[Engine] Failed to close position for {symbol}: {e}")
            return False
    
    def extend_position(self, symbol: str, trail_percent: float) -> bool:
        """
        Replace static stop-loss with trailing stop (orchestrator decision).
        """
        if symbol not in self.positions:
            return False
        
        try:
            order = self.broker.replace_with_trailing_stop(symbol, trail_percent)
            
            pos = self.positions[symbol]
            pos.trailing_stop_order_id = order.id
            pos.extended_bars += 1
            
            logger.info(f"[Engine] Converted {symbol} to trailing stop ({trail_percent}%)")
            
            self.ipc.write_alert(
                alert_type="POSITION_EXTENDED",
                symbol=symbol,
                data={
                    "trail_percent": trail_percent,
                    "original_bars": pos.bars_held,
                    "extension_number": pos.extended_bars,
                },
            )
            
            return True
            
        except Exception as e:
            logger.error(f"[Engine] Failed to extend position {symbol}: {e}")
            return False
    
    def process_commands(self):
        """Process any pending commands from the orchestrator"""
        commands = self.ipc.read_pending_commands()
        
        for cmd in commands:
            logger.info(f"[Engine] Processing command: {cmd.command} for {cmd.symbol}")
            
            if cmd.command == CommandType.CLOSE and cmd.symbol:
                self.close_position(cmd.symbol, "orchestrator_close")
                
            elif cmd.command == CommandType.HOLD:
                # Just acknowledge - continue holding
                logger.info(f"[Engine] Orchestrator says HOLD for {cmd.symbol}")
                
            elif cmd.command == CommandType.REPLACE_SL_TRAIL:
                trail_pct = cmd.params.get("trail_percent", 2.0) if cmd.params else 2.0
                if cmd.symbol:
                    self.extend_position(cmd.symbol, trail_pct)
                    
            elif cmd.command == CommandType.CANCEL_ALL:
                for symbol in list(self.positions.keys()):
                    self.close_position(symbol, "orchestrator_cancel_all")
    
    def process_market_data(self, symbol: str, market_data: Dict):
        """
        Process new market data for a symbol.
        
        This is called when new data arrives (via websocket or polling).
        """
        current_price = market_data.get("close")
        if not current_price:
            return
            
        # Check if we have a position
        if symbol in self.positions:
            position = self.positions[symbol]
            
            # Synthetic Bracket Check (Fractional Trading)
            if position.is_fractional:
                if position.synthetic_tp_price and current_price >= position.synthetic_tp_price:
                    logger.info(f"[Engine] SYNTHETIC Take-Profit Triggered! {symbol} @ {current_price}")
                    self.close_position(symbol, reason="Synthetic Take-Profit")
                    return
                elif position.synthetic_sl_price and current_price <= position.synthetic_sl_price:
                    logger.info(f"[Engine] SYNTHETIC Stop-Loss Triggered! {symbol} @ {current_price}")
                    self.close_position(symbol, reason="Synthetic Stop-Loss")
                    return
            
            # Check for exit signal
            exit_signal = self.evaluate_exit(symbol, market_data, position)
            if exit_signal:
                if exit_signal.metadata.get("force") or exit_signal.action == "exit":
                    self.close_position(symbol, reason=exit_signal.reason)
                    return
            
            # Check for extension criteria
            extension_signal = self.check_extension_criteria(symbol, market_data, position)
            if extension_signal and extension_signal.action == "hold_extension":
                # Alert orchestrator!
                self.ipc.write_alert(
                    alert_type="EXTENSION_NEEDED",
                    symbol=symbol,
                    data=extension_signal.metadata,
                )
                logger.info(f"[Engine] Alerting orchestrator: {extension_signal.reason}")
        
        else:
            # No position - check for entry
            entry_signal = self.evaluate_entry(symbol, market_data)
            if entry_signal:
                # Get current price
                current_price = market_data.get("close")
                if not current_price:
                    return
                
                # Calculate size
                qty = self.calculate_position_size(symbol, current_price)
                
                # Open position
                self.open_position(symbol, qty, current_price)
    
    def run_once(self, market_data_by_symbol: Dict[str, Dict]):
        """
        Run one iteration of the trading loop.
        
        Called by the daemon on each data tick or scheduled interval.
        """
        self.state = EngineState.RUNNING
        
        # Process any commands from orchestrator
        self.process_commands()
        
        # Process each symbol
        for symbol, market_data in market_data_by_symbol.items():
            self.process_market_data(symbol, market_data)
        
        # Update status
        self.ipc.update_status({
            "state": self.state.value,
            "open_positions": list(self.positions.keys()),
            "position_count": len(self.positions),
        })
    
    def get_status(self) -> Dict:
        """Get current engine status"""
        return {
            "state": self.state.value,
            "strategy": self.strategy.get("name"),
            "positions": {
                symbol: {
                    "qty": pos.qty,
                    "entry_price": pos.entry_price,
                    "bars_held": pos.bars_held,
                    "extended": pos.extended_bars > 0,
                }
                for symbol, pos in self.positions.items()
            },
            "config": {
                "max_hold_soft": self.max_hold_soft,
                "max_hold_hard": self.max_hold_hard,
                "stop_loss_pct": self.stop_loss_pct,
                "take_profit_pct": self.take_profit_pct,
            },
        }
    
    def stop(self):
        """Stop the engine"""
        self.state = EngineState.STOPPING
        logger.info("[Engine] Stopping...")
        # Close all positions
        for symbol in list(self.positions.keys()):
            self.close_position(symbol, "engine_stop")
        self.state = EngineState.STOPPED
